name             'awslinuxutil'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures awslinuxutil'
long_description 'Installs/Configures awslinuxutil'
version          '0.1.0'
