name             'awslvm'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures awslvm'
long_description 'Installs/Configures awslvm'
version          '0.1.0'
