driver:
  name: vagrant
  provider: vmware_fusion
  customize:
    numvcpus: 2
    memsize: 2048

provisioner:
  name: chef_zero

platforms:
#  - name: macosx-10.8
#    driver:
#      box: chef/macosx-10.8 # private
#  - name: macosx-10.9
#    driver:
#      box: chef/macosx-10.9 # private
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private