settings:
  parallel: true

driver:
  name: docker
  # privileged is required otherwise the container doesn't boot right
  privileged: true

provisioner:
  name: chef_zero

platforms:
- name: centos-5
- name: centos-6
- name: centos-7
- name: debian-6
  run_list: recipe[apt]
- name: debian-7
  run_list: recipe[apt]
- name: debian-8
  run_list: recipe[apt]
- name: fedora-21
- name: fedora-22
- name: oraclelinux-6
  driver_config:
    platform: rhel
- name: oraclelinux-7
  driver_config:
    platform: rhel
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-15.04
  run_list: recipe[apt]
- name: ubuntu-15.10
  run_list: recipe[apt]
- name: opensuse-13.2

suites:
  - name: default
    data_bags_path: "./test/fixtures/data_bags"
    run_list:
      - recipe[users_test::test_home_dir]
  - name: sysadmins
    run_list:
      - recipe[users::sysadmins]
