---
driver:
  name: dokken
  chef_version: 12.5.1
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false
#  name: inspec

platforms:
# someara/chef container does not support centos-5 yet.
# - name: centos-5
#   driver:
#     image: centos:5

- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-21
  driver:
    image: fedora:21
    intermediate_instructions:
    - RUN yum clean all
    pid_one_command: /usr/lib/systemd/systemd

- name: debian-7
  driver:
    image: debian:7
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

# - name: debian-8
#   driver:
#     image: debian:8
#     pid_one_command: /bin/systemd
#   run_list:
#   - recipe[apt]

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
  run_list:
  - recipe[apt]

# - name: ubuntu-15.04
#   driver:
#     image: ubuntu:15.04
#     pid_one_command: /bin/systemd
#   run_list:
#   - recipe[apt]

suites:

- name: default
  data_bags_path: "./test/fixtures/data_bags"
  run_list:
  - recipe[users_test::test_home_dir]
#
# sysadmins
#
- name: sysadmins
  data_bags_path: "./test/fixtures/data_bags"
  run_list:
  - recipe[users::sysadmins]
  attributes:
    users:
      data_bag: 'test_sysadmin'

